## Dataset ############################################################################################################
### Set input samples list. (Mandatory, one of them or both)
link_directory: links # links by default.
sra_samples: example_sra_samples.tsv ## To access to Sequences Read Archive
local_samples: example_local_samples.tsv ## Local analysis

### Sample processing metadata definition
run_column: seq_run # Column identifying the sequencing run (sequencing error are learned for each run with DADA2)

### Choose the denoising approach, either the "vsearch" to generate classical 97% identity OTUs or the "DADA2" for errors corrected 100% ASVs
denoiser: ["DADA2", "vsearch"] # "vsearch", "DADA2" or both. For ITS (see below) only DADA2 has been tested.

### PCR primers trimming sequences (with PANDAseq for vsearch approach and Cutadapt for DADA2)
Trim_primers: True # False to skip primers trimming (usefull if unkown primers or already trimmed in the input reads, for instance for SRA deposited reads)
ITS_or_16S: 16S # ITS or 16S, affects the primers trimming. With ITS, reverse occurence of the primer is allowed in the opposed read.
min_overlap: 20 # Min overlap of the reads for paired-end reads merging
forward_primer: CCTACGGGNGGCWGCAG # CCTACGGGNGGCWGCAG for Illumina V3V4
reverse_primer: GACTACHVGGGTATCTAATCC # GACTACHVGGGTATCTAATCC for Illumina V3V4

### Merged sequences length-based filtering
merged_min_length: 390 # from 390 to 400 for V3V4
merged_max_length: 480 # from 450 to 500 for V3V4

### DADA2 specific settings ###########################################################################################
#### Trim reads based on length. Reads shorter than this length are trimmed.
DADA2_F_reads_length_trim: 280 # 280 recommended to remove low quality ends of R1. Must be < than read_length - trimmed_primer_length
DADA2_R_reads_length_trim: 255 # 255 recommended to remove low quality ends of R2. Must be < than read_length - trimmed_primer_length

### Filter reads based on number of expected errors after trimming
F_extected_error: 6 # 8 recommended, increase if too much reads are filtered out. Apply to DADA2 approach only
R_extected_error: 6 # 8 recommended, increase if too much reads are filtered out. Apply to DADA2 approach only

### Taxonomic assignment ##############################################################################################
### Reference database
tax_DB: ["Silva132.201908","ezbiocloud201805.201909", "unite201902"] # must be the name of the folder containing files named "DB_amp.fasta" and "DB_amp_taxonomy.txt" in /data/. Can be multiple.
### Taxonimc classifier.
classifier: ["qiimerdp", "dada2rdp","decipher"] # one or more from :"qiimerdp", "dada2rdp","decipher"


## Reads post-processing ##############################################################################################
rarefaction_value: [20000] # value for rarefaction. 20000 is generally enough reads but must be assessed by rarefaction curve.
min_prevalence: [0,10] # proporition (in %) of samples in which the feature has to be found to be kept
min_abundance: [0,100] # minimal count to be kept
normalization: ["CLR", "CSS","TMM", "NONE"] # value for counts normalization. Using script form https://github.com/biobakery/Maaslin2
viz_replace_empty_tax: TRUE # "TRUE" is recommended to replace empty taxonomic levels by "_sp" for species, "_g" for the genus etc.... Otherwise they are left empty
filter_tax_rank: ["Kingdom"] # At which taxonomic rank we filter in. (Usually "Kingdom")
filter_lineage: ["Bacteria"] # What value of filter_tax_rank we keep. (Usually "Bacteria")
filter_out_tax_rank: ["Phylum"] # At which taxonomic rank we filter out. (Usually "Phylum")
filter_out_lineage: ["Bacteria_phy"] # Which value of filter_out_tax_rank we filter out. (Usually "Bacteria_phy" to remove suspicious sequences assigned as Bacteria but which are probably not.

## Visualization ######################################################################################################
grouping_column: ["sample_group"] # Column for which a plot will be generated for each value of.
sample_label: sample_label # Column in "local_samples" used to label samples in output. Cannot be the first column and must be unique. (KRONA, heatmaps, barplots)


## Special outputs ##############################################################################################################
### Phyloseq output for external plitting and analysis
melted_phyloseq: False # Generate melted phyloseq table (voluminous)
phyloseq_tax_ranks: ["OTU"] # Which collapse level for phyloseq output
transposed_tables: False # True to have transposed count table

### Qiime2 Visualization information
Qiime2_basic_output_visualization: True # or False
